# Generated by Django 5.0.2 on 2025-08-12 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this import job", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("invalid_rows", models.PositiveIntegerField(default=0)),
                ("resources_created", models.PositiveIntegerField(default=0)),
                (
                    "column_mapping",
                    models.TextField(
                        blank=True,
                        help_text="JSON mapping of CSV columns to resource fields",
                    ),
                ),
                (
                    "skip_header",
                    models.BooleanField(
                        default=True, help_text="Skip the first row as header"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        help_text="Row number in the CSV file (1-based)"
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        help_text="Field that caused the error",
                        max_length=100,
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("validation", "Validation Error"),
                            ("mapping", "Column Mapping Error"),
                            ("data_type", "Data Type Error"),
                            ("required_field", "Required Field Missing"),
                            ("format", "Format Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(help_text="Detailed error message")),
                (
                    "row_data",
                    models.TextField(
                        blank=True, help_text="JSON representation of the row data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="importer.importjob",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
            },
        ),
    ]
