# Generated by Django 5.0.2 on 2025-08-13 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Service Type",
                "verbose_name_plural": "Service Types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="county",
            field=models.CharField(
                blank=True, help_text="County or parish name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="hours_of_operation",
            field=models.TextField(
                blank=True, help_text="Service hours and availability"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_emergency_service",
            field=models.BooleanField(
                default=False, help_text="Mark if this is a crisis or emergency service"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="service_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Types of services offered by this resource",
                related_name="resources",
                to="directory.servicetype",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["county"], name="directory_r_county_8c43a8_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["is_emergency_service"], name="directory_r_is_emer_0d40db_idx"
            ),
        ),
    ]
