# Generated by Django 5.0.2 on 2025-08-13 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_servicetype_resource_county_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="capacity",
            field=models.CharField(
                blank=True, help_text="Service capacity information", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="cost_information",
            field=models.TextField(
                blank=True, help_text="Financial details and cost information"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="eligibility_requirements",
            field=models.TextField(
                blank=True, help_text="Qualification criteria and requirements"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="insurance_accepted",
            field=models.TextField(
                blank=True, help_text="Insurance plans accepted for medical services"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_24_hour_service",
            field=models.BooleanField(
                default=False, help_text="Mark if this service is available 24/7"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="languages_available",
            field=models.CharField(
                blank=True,
                help_text="Languages supported for accessibility",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="populations_served",
            field=models.TextField(
                blank=True,
                help_text="Target demographics (e.g., veterans, women, children)",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["is_24_hour_service"], name="directory_r_is_24_h_3fc3df_idx"
            ),
        ),
    ]
