# Generated by Django 5.0.2 on 2025-08-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_resource_capacity_resource_cost_information_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Notes and citations for updates and verification"
            ),
        ),
    ]
