# Generated by Django 5.0.2 on 2025-08-13 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0006_add_notes_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="archive_reason",
            field=models.TextField(
                blank=True, help_text="Reason for archiving this resource"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, help_text="When this resource was archived", null=True
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who archived this resource",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_resources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_archived",
            field=models.BooleanField(
                default=False, help_text="Mark if this resource is archived"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["is_archived"], name="directory_r_is_arch_7467db_idx"
            ),
        ),
    ]
