# Generated by Django 5.0.2 on 2025-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0007_add_archive_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="INTERNAL USE ONLY - Notes and citations for updates and verification. This field is NOT visible to the public.",
            ),
        ),
    ]
