# Generated by Django 5.0.2 on 2025-08-19 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0008_update_notes_help_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverageArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CITY", "City"),
                            ("COUNTY", "County"),
                            ("STATE", "State"),
                            ("POLYGON", "Custom Polygon"),
                            ("RADIUS", "Radius"),
                        ],
                        help_text="Type of coverage area",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the coverage area",
                        max_length=200,
                    ),
                ),
                (
                    "radius_m",
                    models.IntegerField(
                        blank=True,
                        help_text="Radius in meters (for radius-based areas)",
                        null=True,
                    ),
                ),
                (
                    "ext_ids",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="External identifiers (e.g., FIPS codes)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_coverage_areas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_coverage_areas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coverage Area",
                "verbose_name_plural": "Coverage Areas",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["kind"], name="directory_c_kind_110627_idx"),
                    models.Index(fields=["name"], name="directory_c_name_f8ccb9_idx"),
                ],
            },
        ),
    ]
