# Generated by Django 5.0.2 on 2025-08-19 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0009_add_coverage_area_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about this resource-coverage area association",
                    ),
                ),
                (
                    "coverage_area",
                    models.ForeignKey(
                        help_text="The coverage area being associated with a resource",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_coverage_associations",
                        to="directory.coveragearea",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this resource-coverage area association",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_resource_coverage_associations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        help_text="The resource being associated with a coverage area",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_coverage_associations",
                        to="directory.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Coverage Association",
                "verbose_name_plural": "Resource Coverage Associations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="coverage_areas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Geographic areas where this resource provides services",
                related_name="resources",
                through="directory.ResourceCoverage",
                to="directory.coveragearea",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcecoverage",
            index=models.Index(
                fields=["resource"], name="directory_r_resourc_f18d00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourcecoverage",
            index=models.Index(
                fields=["coverage_area"], name="directory_r_coverag_98dee0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourcecoverage",
            index=models.Index(
                fields=["created_at"], name="directory_r_created_deacea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourcecoverage",
            index=models.Index(
                fields=["created_by"], name="directory_r_created_01a050_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resourcecoverage",
            unique_together={("resource", "coverage_area")},
        ),
    ]
