# Generated by Django 5.0.2 on 2025-08-19 22:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0010_add_resource_coverage_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="coveragearea",
            name="center",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="coveragearea",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
