# Generated by Django 5.0.2 on 2025-08-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0010_add_resource_coverage_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="coveragearea",
            name="center",
            field=models.TextField(
                blank=True, null=True, help_text="Center point coordinates (JSON format when GIS disabled)"
            ),
        ),
        migrations.AddField(
            model_name="coveragearea",
            name="geom",
            field=models.TextField(
                blank=True, null=True, help_text="Geometry data (JSON format when GIS disabled)"
            ),
        ),
    ]
