# Generated by Django 5.0.2 on 2025-08-19 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0011_add_spatial_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="coveragearea",
            new_name="coverage_area_kind_idx",
            old_name="directory_c_kind_110627_idx",
        ),
        migrations.RenameIndex(
            model_name="coveragearea",
            new_name="coverage_area_name_idx",
            old_name="directory_c_name_f8ccb9_idx",
        ),
        migrations.AddIndex(
            model_name="coveragearea",
            index=models.Index(
                fields=["kind", "name"], name="coverage_area_kind_name_idx"
            ),
        ),
    ]
