# Generated by Django 5.0.2 on 2025-08-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0012_add_coverage_area_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeocodingCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the geocoding query",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "query",
                    models.TextField(help_text="Original geocoding query string"),
                ),
                ("latitude", models.FloatField(help_text="Latitude coordinate")),
                ("longitude", models.FloatField(help_text="Longitude coordinate")),
                (
                    "address",
                    models.TextField(
                        help_text="Formatted address from geocoding service"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Name of the geocoding provider used", max_length=50
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence score (0.0-1.0) from the provider",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this cache entry expires"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this cache entry was created"
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this cache entry has been accessed",
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this cache entry was last accessed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geocoding Cache Entry",
                "verbose_name_plural": "Geocoding Cache Entries",
                "ordering": ["-last_accessed"],
                "indexes": [
                    models.Index(
                        fields=["query_hash"], name="directory_g_query_h_dd2aca_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="directory_g_expires_684b6d_idx"
                    ),
                    models.Index(
                        fields=["provider"], name="directory_g_provide_fd9dda_idx"
                    ),
                    models.Index(
                        fields=["last_accessed"], name="directory_g_last_ac_1465e0_idx"
                    ),
                ],
            },
        ),
    ]
