# Generated by Django 5.0.2 on 2025-08-21 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0013_geocodingcache"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date for this analytics record")),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        help_text="Type of analytics period",
                        max_length=20,
                    ),
                ),
                (
                    "total_searches",
                    models.IntegerField(
                        default=0, help_text="Total number of searches"
                    ),
                ),
                (
                    "unique_addresses",
                    models.IntegerField(
                        default=0, help_text="Number of unique addresses searched"
                    ),
                ),
                (
                    "avg_results_per_search",
                    models.FloatField(
                        default=0.0, help_text="Average results per search"
                    ),
                ),
                (
                    "avg_search_duration_ms",
                    models.FloatField(default=0.0, help_text="Average search duration"),
                ),
                (
                    "geocoding_success_rate",
                    models.FloatField(
                        default=0.0, help_text="Geocoding success rate percentage"
                    ),
                ),
                (
                    "top_locations",
                    models.JSONField(default=list, help_text="Top searched locations"),
                ),
                (
                    "radius_distribution",
                    models.JSONField(
                        default=dict, help_text="Search radius usage distribution"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "search_analytics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["date", "period_type"],
                        name="search_anal_date_3af00f_idx",
                    )
                ],
                "unique_together": {("date", "period_type")},
            },
        ),
        migrations.CreateModel(
            name="LocationSearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Original search address", max_length=255
                    ),
                ),
                (
                    "lat",
                    models.FloatField(
                        blank=True, help_text="Geocoded latitude", null=True
                    ),
                ),
                (
                    "lon",
                    models.FloatField(
                        blank=True, help_text="Geocoded longitude", null=True
                    ),
                ),
                (
                    "radius_miles",
                    models.FloatField(default=10.0, help_text="Search radius in miles"),
                ),
                (
                    "results_count",
                    models.IntegerField(
                        default=0, help_text="Number of results returned"
                    ),
                ),
                (
                    "search_duration_ms",
                    models.IntegerField(
                        default=0, help_text="Search execution time in milliseconds"
                    ),
                ),
                (
                    "geocoding_success",
                    models.BooleanField(
                        default=True, help_text="Whether geocoding was successful"
                    ),
                ),
                (
                    "geocoding_provider",
                    models.CharField(
                        default="nominatim",
                        help_text="Geocoding service used",
                        max_length=50,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the search was performed"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the search",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "location_search_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["address"], name="location_se_address_0a2f60_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="location_se_created_dd7bc5_idx"
                    ),
                    models.Index(
                        fields=["geocoding_success"],
                        name="location_se_geocodi_5e15c9_idx",
                    ),
                    models.Index(
                        fields=["radius_miles"], name="location_se_radius__dd2af5_idx"
                    ),
                ],
            },
        ),
    ]
