# Generated by Django 5.0.2 on 2025-08-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0014_add_search_analytics"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="verification_frequency_days",
            field=models.IntegerField(
                default=180,
                help_text="Number of days between verifications (default: 180 days = 6 months)",
            ),
        ),
    ]
