# Generated by Django 5.0.2 on 2025-08-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0015_resource_verification_frequency_days"),
    ]

    operations = []
