# Generated by Django 5.0.2 on 2025-08-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0017_remove_fts5_search"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coveragearea",
            name="center",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="geom",
            field=models.TextField(blank=True, null=True),
        ),
    ]
