# Generated by Django 5.0.2 on 2025-08-26 01:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0018_alter_coveragearea_center_alter_coveragearea_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coveragearea",
            name="center",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
